### PR TITLE
Ignore zero-length Ogg packets

### PR DESCRIPTION
**Pull request by mcf06**
Some encoders (e.g. Concentus) sometimes generate zero-length packets at the end of a stream. The reference tool opusinfo notes this and ignores the packet:

"WARNING: Invalid zero byte packet in stream 1"

However, magnum-rs tries to access the first byte without checking the packet length, resulting in a panic:

magnum-1.0.0/src/container/ogg.rs:85:54:
range end index 1 out of range for slice of length 0

This fix detects and ignores zero-length packets.

### CODE REVIEW

**Comment by seratonik** [comment]
Thank you for this! I'll try get it merged and released as soon as I have some time!

**Comment by mcf06** [comment]
@seratonik : Could I politely nudge you to pop out that release? :)

**Comment by seratonik** [comment]
@mcf06 so sorry for the delay! life got in the way for a bit there - I'll jump on this right now

**Comment by seratonik** [comment]
@mcf06 I've merged this in with the crates.io version of the library to make 1.0.1 (https://crates.io/crates/magnum/1.0.1). I'll also bring them into the upcoming 1.1.0 branch here before it ever gets pushed to crates (it basically updates the kira/rodio integrations, but doesn't touch the core)

Thanks again for making this fix and sorry for it taking so long to merge!

**Comment by mcf06** [comment]
That's great, thank you!

**Pull request merged**
